// <auto-generated />
namespace SC_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class identityframeworkproto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identityframeworkproto));
        
        string IMigrationMetadata.Id
        {
            get { return "202007120050525_identity-framework-proto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
